Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2020-11, with the labels that each got.

#12 Adding in-tree glossary for definitions
  proposals/00_capn-glossary.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#13 :sparkles: Add foundation tooling and files
  .dockerignore
  .gitignore
  .golangci.yml
  Makefile
  PROJECT
  cloudbuild.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/boilerplate/boilerplate.Makefile.txt
  hack/boilerplate/boilerplate.bzl.txt
  hack/boilerplate/boilerplate.generatebzl.txt
  hack/boilerplate/boilerplate.generatego.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.py
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/boilerplate/boilerplate_test.py
  hack/boilerplate/test/fail.go
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.go
  hack/boilerplate/test/pass.py
  hack/ensure-go.sh
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  hack/ensure-kustomize.sh
  hack/pin-dependency.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/utils.sh
  hack/verify-boilerplate.sh
  hack/verify-doctoc.sh
  hack/verify-shellcheck.sh
  hack/verify-starlark.sh
  hack/version.sh
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#16 ⚠️ changing flag names
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#17 Add terms to CAPN glossary
  proposals/00_capn-glossary.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#11 Proposal: define the CRD of nested components
  proposals/20201026-creating-control-plane-components.md
  proposals/in-tree.png
  proposals/out-of-tree.png
Labels: approved, cncf-cla: yes, kind/design, priority/important-soon, size/L
