Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2020-12, with the labels that each got.

#24 Add scaffolding
  PROJECT
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/nestedcontrolplane_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/controlplane.cluster.x.k8s.io_nestedcontrolplanes.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_nestedcontrolplanes.yaml
  config/crd/patches/webhook_in_nestedcontrolplanes.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/nestedcontrolplane_editor_role.yaml
  config/rbac/nestedcontrolplane_viewer_role.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/service.yaml
  controllers/nestedcontrolplane_controller.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#25 Switch to proper x-k8s.io domain
  PROJECT
  api/v1alpha4/groupversion_info.go
  config/crd/bases/controlplane.cluster.x.k8s.io_nestedcontrolplanes.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_nestedcontrolplanes.yaml
  config/crd/patches/webhook_in_nestedcontrolplanes.yaml
  config/rbac/nestedcontrolplane_editor_role.yaml
  config/rbac/nestedcontrolplane_viewer_role.yaml
  config/rbac/role.yaml
  controllers/nestedcontrolplane_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#27 Updating controller-runtime to 0.7.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XS

#26 Moving api -> apis and setting multigroup: true
  Dockerfile
  PROJECT
  apis/controlplane/v1alpha4/groupversion_info.go
  apis/controlplane/v1alpha4/nestedcontrolplane_types.go
  apis/controlplane/v1alpha4/zz_generated.deepcopy.go
  controllers/controlplane/nestedcontrolplane_controller.go
  controllers/controlplane/suite_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/M
