Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2021-07, with the labels that each got.

#151 Correct the description for crd syncer
  virtualcluster/doc/customresource-syncer.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#158 Disable nodelifecycle controller to void NotReady status of virtual node
  controlplane/nested/component-templates/nested-controllermanager/nested-controllermanager-statefulset-template.yaml
  virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
  virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
  virtualcluster/pkg/controller/controllers/clusterversion_controller_test.go
  virtualcluster/test/e2e/framework/clusterversion/create.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#153 Add permission for secret deletecollect
  virtualcluster/config/setup/all_in_one.yaml
  virtualcluster/config/setup/all_in_one_aliyun.yaml
  virtualcluster/config/setup/all_in_one_capi.yaml
  virtualcluster/doc/customresource-syncer.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#157 ✨ Add certmanager flavor
  templates/cluster-template-certmanager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#161 Remove old webhookconfiguration if it alreasy exist before create new one
  virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#160 Avoid to diff ClusterIPs for SVC sync
  virtualcluster/pkg/syncer/conversion/equality.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#163 Terminal informer after tenant cluster removed
  virtualcluster/pkg/util/cluster/cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#173 update doc to make proxy step optional
  virtualcluster/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#174 📖Add info about usage of kubectl vc exec
  virtualcluster/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#175 Update variable name for fpcert
  controlplane/nested/controllers/nestedapiserver_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#167 ✨ Enabled Aggregate API for Virtual Cluster
  virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
  virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
  virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
  virtualcluster/pkg/controller/pki/pki.go
  virtualcluster/pkg/controller/secret/secret.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#172 🌱 Add useful information for patroller log lines
  virtualcluster/pkg/syncer/resources/configmap/checker.go
  virtualcluster/pkg/syncer/resources/crd/checker.go
  virtualcluster/pkg/syncer/resources/endpoints/checker.go
  virtualcluster/pkg/syncer/resources/ingress/checker.go
  virtualcluster/pkg/syncer/resources/namespace/checker.go
  virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  virtualcluster/pkg/syncer/resources/pod/checker.go
  virtualcluster/pkg/syncer/resources/priorityclass/checker.go
  virtualcluster/pkg/syncer/resources/secret/checker.go
  virtualcluster/pkg/syncer/resources/service/checker.go
  virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
  virtualcluster/pkg/syncer/resources/storageclass/checker.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#178 🐛 add ipFamilies and ipFamilyPolicy into sync pre-set
  virtualcluster/pkg/syncer/conversion/equality.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#179 Use front-proxy-client CN for aggregate API
  virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
  virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#180 Enabled aggregate API for nested controller
  controlplane/nested/component-templates/nested-apiserver/nested-apiserver-statefulset-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#186 Added a dev quick start guide
  docs/dev-quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#187 Correct the value for requestheader-client-ca-file
  controlplane/nested/component-templates/nested-apiserver/nested-apiserver-statefulset-template.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#191 🌱 Update for picking up cluster-api v0.4.0
  controlplane/nested/certificate/keypairs_test.go
  controlplane/nested/main.go
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#196 Correct sample for crd syncer
  virtualcluster/doc/customresource-syncer.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#193 Remove restart.sh and start.sh in docker file
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#194 ✨ Add webhook framework
  api/v1alpha4/nestedcluster_webhook.go
  api/v1alpha4/nestedcluster_webhook_test.go
  api/v1alpha4/webhooks.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#192 📖add minikube info into dev doc
  docs/dev-quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/M
