Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2021-08, with the labels that each got.

#200 ✨ Watch instead of loop check nested cluster
  controllers/nestedcluster_controller.go
  main.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#202 vc-syncer: remove invalid cluster name from knownClusterSet
  virtualcluster/pkg/syncer/resources/pod/checker.go
  virtualcluster/pkg/syncer/resources/service/checker.go
  virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
Labels: ok-to-test, size/XS, cncf-cla: yes, approved, lgtm

#205 Remove related kubeconfig file when exit
  virtualcluster/cmd/kubectl-vc/exec.go
Labels: ok-to-test, size/XS, cncf-cla: yes, approved, lgtm

#207 ✨ update healthy from ping to webhook server check
  go.mod
  go.sum
  main.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#211 🌱 add test for "Enabled Aggregate API for Virtual Cluster"
  virtualcluster/pkg/controller/controllers/clusterversion_controller_test.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/S
