Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2021-05, with the labels that each got.

#48 🌱 Adding scripts directory for prow jobs
  .gitignore
  .golangci.yml
  Makefile
  apis/controlplane/v1alpha4/nestedcomponent_types.go
  config/samples/controlplane_v1alpha4_nestedapiserver.yaml
  config/samples/controlplane_v1alpha4_nestedcontrollermanager.yaml
  config/samples/controlplane_v1alpha4_nestedcontrolplane.yaml
  config/samples/controlplane_v1alpha4_nestedetcd.yaml
  config/samples/infrastructure_v1alpha4_nestedcluster.yaml
  config/samples/v1alpha4_cluster.yaml
  controllers/controlplane/nestedetcd_controller.go
  scripts/ci-build.sh
  scripts/ci-make.sh
  scripts/ci-test.sh
  scripts/fetch_ext_bins.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#51 Do not add slash for REGISTRY with non google cloud
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#49 🌱 Reenabling more Lint tasks
  .golangci.yml
  Makefile
  apis/controlplane/v1alpha4/nestedcontrolplane_types.go
  certificate/helpers.go
  certificate/keypairs.go
  controllers/controlplane/controller_util.go
  controllers/controlplane/nestedcontrolplane_controller.go
  controllers/infrastructure/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#55 [VC] unset the VC validation webhook CABundle
  virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#56 fix ineffectual assignment to err
  virtualcluster/cmd/kubectl-vc/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#58 doc: add quick start guide for CAPN
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#66 🐛 fixing branch name for apidiff
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#68 ✨ Adding virtualcluster to prow
  scripts/ci-build.sh
  scripts/ci-make.sh
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#73 Bugfix: fix error in quick start guide
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#72 Setting kind name as CAPN
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#76 updated how to connect to cluster
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#82 Adjust VirtualCluster owners
  virtualcluster/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
