Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2021-04, with the labels that each got.

#38 Update NCP types
  apis/controlplane/v1alpha4/nestedcontrolplane_types.go
  apis/controlplane/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_nestedcontrolplanes.yaml
Labels: approved, cncf-cla: yes, size/L

#39 Add charleszheng44 to Approvers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#40 Implement the NestedControllerManager controller
  PROJECT
  apis/controlplane/v1alpha4/nestedcontrollermanager_types.go
  apis/controlplane/v1alpha4/zz_generated.deepcopy.go
  config/component-templates/nested-apiserver/nested-apiserver-statefulset-template.yaml
  config/component-templates/nested-controllermanager/nested-controllermanager-statefulset-template.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_nestedcontrollermanagers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_nestedcontrollermanagers.yaml
  config/crd/patches/webhook_in_nestedcontrollermanagers.yaml
  config/rbac/nestedcontrollermanager_editor_role.yaml
  config/rbac/nestedcontrollermanager_viewer_role.yaml
  config/rbac/role.yaml
  controllers/controlplane/controller_util.go
  controllers/controlplane/nestedcontrollermanager_controller.go
  controllers/controlplane/suite_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#42 Fix bugs of nestedcomponent controllers
  apis/controlplane/v1alpha4/nestedapiserver_types.go
  apis/controlplane/v1alpha4/nestedcontrollermanager_types.go
  config/component-templates/nested-apiserver/nested-apiserver-statefulset-template.yaml
  config/component-templates/nested-controllermanager/nested-controllermanager-statefulset-template.yaml
  config/component-templates/nested-etcd/nested-etcd-service-template.yaml
  config/component-templates/nested-etcd/nested-etcd-statefulset-template.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_nestedapiservers.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_nestedcontrollermanager.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_nestedapiservers.yaml
  config/crd/patches/cainjection_in_nestedcontrollermanagers.yaml
  config/crd/patches/cainjection_in_nestedcontrolplanes.yaml
  config/crd/patches/cainjection_in_nestedetcds.yaml
  config/crd/patches/webhook_in_nestedapiservers.yaml
  config/crd/patches/webhook_in_nestedcontrollermanagers.yaml
  config/crd/patches/webhook_in_nestedcontrolplanes.yaml
  config/crd/patches/webhook_in_nestedetcds.yaml
  controllers/controlplane/consts.go
  controllers/controlplane/controller_util.go
  controllers/controlplane/nestedapiserver_controller.go
  controllers/controlplane/nestedcontrollermanager_controller.go
  controllers/controlplane/nestedetcd_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L
