Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2021-11, with the labels that each got.

#233 📖 Update documentation for DisableServiceAccountToken
  virtualcluster/cmd/syncer/app/options/options.go
  virtualcluster/pkg/syncer/apis/config/types.go
Labels: ok-to-test, size/XS, cncf-cla: yes, approved, lgtm

#232 🐛 VC-Syncer - remove check for optional secret Volumes on Pods
  virtualcluster/pkg/syncer/resources/pod/dws.go
  virtualcluster/pkg/syncer/resources/pod/dws_test.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/S

#228 Remove additional space in PROJECT file
  controlplane/nested/PROJECT
Labels: ok-to-test, size/XS, cncf-cla: yes, approved, lgtm

#234 Correct crd link for experiment
  virtualcluster/experiment/doc/demo.md
Labels: ok-to-test, size/XS, cncf-cla: yes, approved, lgtm

#216 ✨ Generate the manifests by calling the kubeadm
  Dockerfile
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/samples/infrastructure_v1alpha4_nestedcluster.yaml
  config/samples/v1alpha4_cluster.yaml
  controlplane/nested/component-templates/nested-apiserver/nested-apiserver-service-template.yaml
  controlplane/nested/component-templates/nested-apiserver/nested-apiserver-statefulset-template.yaml
  controlplane/nested/component-templates/nested-controllermanager/nested-controllermanager-statefulset-template.yaml
  controlplane/nested/component-templates/nested-etcd/nested-etcd-service-template.yaml
  controlplane/nested/component-templates/nested-etcd/nested-etcd-statefulset-template.yaml
  controlplane/nested/config/crd/kustomization.yaml
  controlplane/nested/config/rbac/role.yaml
  controlplane/nested/controllers/consts.go
  controlplane/nested/controllers/controller_util.go
  controlplane/nested/controllers/nestedapiserver_controller.go
  controlplane/nested/controllers/nestedcontrollermanager_controller.go
  controlplane/nested/controllers/nestedcontrolplane_controller.go
  controlplane/nested/controllers/nestedetcd_controller.go
  controlplane/nested/kubeadm/consts.go
  controlplane/nested/kubeadm/kubeadm.go
  controlplane/nested/main.go
  go.mod
Labels: cncf-cla: yes, approved, lgtm, size/XXL
