Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2021-03, with the labels that each got.

#29 NestedControlPlane & NestedCluster Proposal
  docs/Makefile
  docs/proposals/00_capn-glossary.md
  docs/proposals/20201026-creating-control-plane-components.md
  docs/proposals/20210126-nc-and-ncp.md
  docs/proposals/YYYYMMDD-template.md
  docs/proposals/images/componentcontrollers/in-tree.png
  docs/proposals/images/componentcontrollers/out-of-tree.png
  docs/proposals/images/nestedcontrolplane/nc-activity.plantuml
  docs/proposals/images/nestedcontrolplane/nc-activity.png
  docs/proposals/images/nestedcontrolplane/ncp-activity.plantuml
  docs/proposals/images/nestedcontrolplane/ncp-activity.png
  docs/proposals/out-of-tree.png
Labels: approved, cncf-cla: yes, size/XL

#36 Update klog dependency to v2
  go.mod
  go.sum
  hack/tools/go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#30 Implement the NestedEtcd controller
  Makefile
  apis/controlplane/v1alpha4/nestedcomponentspec_types.go
  apis/controlplane/v1alpha4/nestedetcd_types.go
  apis/controlplane/v1alpha4/zz_generated.deepcopy.go
  config/component-templates/nested-etcd/nested-etcd-service-template.yaml
  config/component-templates/nested-etcd/nested-etcd-statefulset-template.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_nestedetcds.yaml
  config/rbac/role.yaml
  controllers/controlplane/nestedetcd_controller.go
  controllers/controlplane/nestedetcd_controller_test.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL
