Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2021-06, with the labels that each got.

#83 syncer: check meta equality for sa type token secret
  virtualcluster/pkg/syncer/conversion/equality.go
Labels: approved, cncf-cla: yes, size/S

#84 🌱 Adding new/updated ClusterVersion and VirtualCluster test suites
  virtualcluster/cmd/manager/main.go
  virtualcluster/config/crd/tenancy.x-k8s.io_clusterversions.yaml
  virtualcluster/pkg/controller/add_virtualcluster.go
  virtualcluster/pkg/controller/clusterversion/clusterversion_controller_suite_test.go
  virtualcluster/pkg/controller/clusterversion/clusterversion_controller_test.go
  virtualcluster/pkg/controller/controller.go
  virtualcluster/pkg/controller/controllers/clusterversion_controller.go
  virtualcluster/pkg/controller/controllers/clusterversion_controller_test.go
  virtualcluster/pkg/controller/controllers/provisioner/provisioner.go
  virtualcluster/pkg/controller/controllers/provisioner/provisioner_aliyun.go
  virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
  virtualcluster/pkg/controller/controllers/suite_test.go
  virtualcluster/pkg/controller/controllers/virtualcluster_controller.go
  virtualcluster/pkg/controller/controllers/virtualcluster_controller_test.go
  virtualcluster/pkg/controller/vcmanager/vcmanager.go
  virtualcluster/pkg/controller/virtualcluster/master_provisioner.go
  virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller_suite_test.go
  virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, size/XXL

#86 Install binaries for envTest
  virtualcluster/Makefile
  virtualcluster/config/crds/cluster.x-k8s.io_clusters.yaml
  virtualcluster/config/crds/tenancy.x-k8s.io_clusterversions.yaml
  virtualcluster/config/crds/tenancy.x-k8s.io_virtualclusters.yaml
  virtualcluster/doc/demo.md
  virtualcluster/experiment/doc/demo.md
  virtualcluster/hack/lib/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#87 🌱 VN Agent Healthz Checks
  virtualcluster/cmd/vn-agent/app/options/options.go
  virtualcluster/cmd/vn-agent/app/server.go
  virtualcluster/go.sum
  virtualcluster/pkg/controller/controllers/suite_test.go
  virtualcluster/pkg/vn-agent/server/server.go
  virtualcluster/pkg/vn-agent/server/test/go.sum
  virtualcluster/pkg/vn-agent/server/test/server_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#88 🌱 [VC] Adding go:1.16.2 docker image for VC
  virtualcluster/Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#90 🌱 Upgrade Golang CI & Fix Lint
  .golangci.yml
  Makefile
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/nestedcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_nestedclusters.yaml
  controllers/nestedcluster_controller.go
  controlplane/nested/api/v1alpha4/groupversion_info.go
  controlplane/nested/api/v1alpha4/nestedapiserver_types.go
  controlplane/nested/api/v1alpha4/nestedcomponent_types.go
  controlplane/nested/api/v1alpha4/nestedcontrollermanager_types.go
  controlplane/nested/api/v1alpha4/nestedcontrolplane_types.go
  controlplane/nested/api/v1alpha4/nestedetcd_types.go
  controlplane/nested/certificate/consts.go
  controlplane/nested/certificate/helpers.go
  controlplane/nested/certificate/keypair.go
  controlplane/nested/certificate/keypairs.go
  controlplane/nested/certificate/keypairs_test.go
  controlplane/nested/certificate/types.go
  controlplane/nested/certificate/util/util.go
  controlplane/nested/config/crd/bases/controlplane.cluster.x-k8s.io_nestedapiservers.yaml
  controlplane/nested/config/crd/bases/controlplane.cluster.x-k8s.io_nestedcontrollermanagers.yaml
  controlplane/nested/config/crd/bases/controlplane.cluster.x-k8s.io_nestedcontrolplanes.yaml
  controlplane/nested/config/crd/bases/controlplane.cluster.x-k8s.io_nestedetcds.yaml
  controlplane/nested/config/rbac/role.yaml
  controlplane/nested/controllers/consts.go
  controlplane/nested/controllers/controller_util.go
  controlplane/nested/controllers/controller_util_test.go
  controlplane/nested/controllers/nestedapiserver_controller.go
  controlplane/nested/controllers/nestedcontrollermanager_controller.go
  controlplane/nested/controllers/nestedcontrolplane_controller.go
  controlplane/nested/controllers/nestedetcd_controller.go
  controlplane/nested/main.go
  hack/boilerplate/test/fail.go
  hack/ensure-golangci-lint.sh
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
  virtualcluster/pkg/controller/pki/pki.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XXL

#92 Updating staging and prod registries
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#93 🐛 Updating staging and prod registries
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#95 🐛 target manifest pointed to wrong directory
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#100 🐛 control plane manifests weren't being pushed
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#102 🐛 removing docker/infra provider from cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#103 🐛 removing docker/infra provider from cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#104 Fix incorrect git address
  virtualcluster/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#108 🍒 Cherrypick #106 🐛 Remove make release-binaries from make release
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#107 🐛 Remove make release-binaries from make release
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#111 🐛 remove docker release references
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#113 🐛 control plane manifests generated
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#114 🍒 Cherry Pick 🐛 control plane manifests generated
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#115 🐛 Fix permission issues and wrong control plane image
  Makefile
  config/manager/manager.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  controlplane/nested/config/manager/manager.yaml
  controlplane/nested/config/rbac/auth_proxy_role_binding.yaml
  controlplane/nested/config/rbac/kustomization.yaml
  controlplane/nested/config/rbac/leader_election_role_binding.yaml
  controlplane/nested/config/rbac/role_binding.yaml
  controlplane/nested/config/rbac/service_account.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#116 🐛 Fix permission issues and wrong control plane image
  Makefile
  config/manager/manager.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  controlplane/nested/config/manager/manager.yaml
  controlplane/nested/config/rbac/auth_proxy_role_binding.yaml
  controlplane/nested/config/rbac/kustomization.yaml
  controlplane/nested/config/rbac/leader_election_role_binding.yaml
  controlplane/nested/config/rbac/role_binding.yaml
  controlplane/nested/config/rbac/service_account.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#122 🐛Fix the issue of make release-notes in cluster-api-provider-nested
  Makefile
  hack/tools/release/notes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#120 🐛 metadata.yaml clusterctl version to v1alpha3
  metadata.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#123 🌱 Add .github directory from CAPI
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#126 ✨ Adding cluster-template.yaml for clusterctl
  Makefile
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#127 Update README to reflect latest code and way for init
  docs/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#138 syncer: remedy for missmatched endpoints
  virtualcluster/pkg/syncer/resources/endpoints/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#139 syncer: remove feature guard when checking ns meta equality
  virtualcluster/pkg/syncer/resources/namespace/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#140 Remove ValidatingWebhookConfiguration when clearing all virtual cluster stuff
  virtualcluster/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#136 ✨ Adding CAPI Provisioner to vc-manager
  controllers/nestedcluster_controller.go
  templates/cluster-template-virtualcluster.yaml
  virtualcluster/cmd/manager/main.go
  virtualcluster/config/crd/cluster.x-k8s.io_clusters.yaml
  virtualcluster/config/rbac/role.yaml
  virtualcluster/config/sampleswithspec/virtualcluster_capi.yaml
  virtualcluster/config/setup/all_in_one_capi.yaml
  virtualcluster/go.mod
  virtualcluster/go.sum
  virtualcluster/pkg/controller/constants/constants.go
  virtualcluster/pkg/controller/controller.go
  virtualcluster/pkg/controller/controllers/capi_virtualcluster_controller.go
  virtualcluster/pkg/controller/controllers/clusterversion_controller.go
  virtualcluster/pkg/controller/controllers/virtualcluster_controller.go
  virtualcluster/pkg/syncer/constants/constants.go
  virtualcluster/pkg/syncer/conversion/helper.go
  virtualcluster/pkg/vn-agent/server/test/go.mod
  virtualcluster/pkg/vn-agent/server/test/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#142 Correct manifest path since the file name has been changed in previously ccommit
  virtualcluster/doc/demo.md
  virtualcluster/experiment/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#144 🐛 Adding back original all_in_one.yaml for VC
  virtualcluster/config/setup/all_in_one.yaml
  virtualcluster/doc/demo.md
  virtualcluster/experiment/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#145 🐛 use self-signed certificate for the virtualcluster webhook server
  virtualcluster/config/setup/all_in_one.yaml
  virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#147 update to reflect v0.4.0 cluster api
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#149 Do not need to clone the repo before test
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#148 Correct Kind setting for MultiClusterController
  virtualcluster/pkg/util/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
