Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2022-10, with the labels that each got.

#317 ✨Bypass vc-syncing if tenant has own scheduler and dedicated node.
  virtualcluster/pkg/syncer/constants/constants.go
  virtualcluster/pkg/syncer/resources/pod/checker.go
  virtualcluster/pkg/syncer/resources/pod/dws.go
  virtualcluster/pkg/syncer/util/featuregate/gate.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#321 🐛 Handle deprecated preserveUnknownField in CRD spec
  virtualcluster/pkg/syncer/conversion/helper.go
  virtualcluster/pkg/syncer/util/featuregate/gate.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/M

#323 ✨ Add PersistentVolumeClaim status UWS
  virtualcluster/pkg/syncer/conversion/equality.go
  virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  virtualcluster/pkg/syncer/resources/persistentvolumeclaim/uws.go
  virtualcluster/pkg/syncer/resources/persistentvolumeclaim/uws_test.go
Labels: kind/feature, ok-to-test, cncf-cla: yes, size/L, approved, lgtm
