Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2022-11, with the labels that each got.

#326 🐛 v1.21 Support for RootCACertConfigMap feature
  virtualcluster/pkg/syncer/constants/constants.go
  virtualcluster/pkg/syncer/conversion/equality.go
  virtualcluster/pkg/syncer/conversion/helper.go
  virtualcluster/pkg/syncer/resources/configmap/checker.go
  virtualcluster/pkg/syncer/resources/configmap/checker_test.go
  virtualcluster/pkg/syncer/resources/configmap/dws.go
  virtualcluster/pkg/syncer/resources/configmap/dws_test.go
  virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator.go
  virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator_test.go
  virtualcluster/pkg/syncer/util/featuregate/gate.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#327 🐛 Fix servcie mutator, reset pService ClusterIPs
  virtualcluster/pkg/syncer/conversion/mutate.go
  virtualcluster/pkg/syncer/resources/service/dws_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#328 🐛 InitContainer support for kube-root-ca.crt ConfigMaps
  virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator.go
  virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#331 🌱 Adding Cluster Labels w/ Control Plane Components
  virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#330 ✨ Enhancement for virtual cluster DNS
  virtualcluster/config/sampleswithspec/coredns_external.yaml
  virtualcluster/pkg/controller/controllers/virtualcluster_controller_test.go
  virtualcluster/pkg/syncer/conversion/equality.go
  virtualcluster/pkg/syncer/resources/service/uws.go
  virtualcluster/pkg/syncer/util/featuregate/gate.go
Labels: ok-to-test, cncf-cla: yes, size/L, approved, lgtm
