Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2022-09, with the labels that each got.

#301 🌱 Update samples with k8s 1.22 and apiVersions
  virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
  virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#302 🌱 Add etcd.namespace to the etcd certificate
  virtualcluster/pkg/client/clientset/versioned/fake/register.go
  virtualcluster/pkg/client/clientset/versioned/scheme/register.go
  virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
  virtualcluster/pkg/syncer/resources/namespace/checker.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#303 🌱 Update Ingress Syncer for v1.20 support
  virtualcluster/pkg/syncer/conversion/equality.go
  virtualcluster/pkg/syncer/resources/ingress/checker.go
  virtualcluster/pkg/syncer/resources/ingress/checker_test.go
  virtualcluster/pkg/syncer/resources/ingress/controller.go
  virtualcluster/pkg/syncer/resources/ingress/dws.go
  virtualcluster/pkg/syncer/resources/ingress/dws_test.go
  virtualcluster/pkg/syncer/resources/ingress/uws.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#306 🐛 Handle GetCluster == nil in CRD uws
  virtualcluster/pkg/syncer/resources/crd/checker.go
  virtualcluster/pkg/syncer/resources/crd/uws.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#305 ✨ Sync node taints and labels
  virtualcluster/cmd/syncer/app/options/options.go
  virtualcluster/pkg/syncer/apis/config/types.go
  virtualcluster/pkg/syncer/resources/node/uws.go
  virtualcluster/pkg/syncer/vnode/native/provider.go
  virtualcluster/pkg/syncer/vnode/native/provider_test.go
  virtualcluster/pkg/syncer/vnode/pod/provider.go
  virtualcluster/pkg/syncer/vnode/provider/provider.go
  virtualcluster/pkg/syncer/vnode/service/provider.go
  virtualcluster/pkg/syncer/vnode/vnode.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#307 🐛 Add Annotation UID of pPV to be synced to vPV
  virtualcluster/pkg/syncer/conversion/helper.go
  virtualcluster/pkg/syncer/resources/persistentvolume/uws_test.go
Labels: kind/bug, ok-to-test, size/XS, cncf-cla: yes, approved, lgtm

#310 Fix Pod Checker occasionally deletes vPods unexpectedly
  virtualcluster/pkg/syncer/resources/pod/checker.go
Labels: size/XS, cncf-cla: yes, needs-ok-to-test, approved, lgtm

#314 ✨ Convert PodMutators to Plugins
  virtualcluster/pkg/syncer/conversion/mutate.go
  virtualcluster/pkg/syncer/conversion/mutate_test.go
  virtualcluster/pkg/syncer/resources/pod/controller.go
  virtualcluster/pkg/syncer/resources/pod/dws.go
  virtualcluster/pkg/syncer/resources/pod/mutatorplugin/interface.go
  virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podmountserviceaccounttokenmutator.go
  virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podservicelinkmutator.go
Labels: cncf-cla: yes, size/L, approved, lgtm
