Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2022-02, with the labels that each got.

#242 🌱 Add additionalPrinterColumns to VirtualCluster CRD
  virtualcluster/config/crd/tenancy.x-k8s.io_virtualclusters.yaml
  virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/S

#243 🌱 Configurable wait time on VirtualCluster Controller for control plane bring up
  virtualcluster/cmd/manager/main.go
  virtualcluster/pkg/controller/controller.go
  virtualcluster/pkg/controller/controllers/provisioner/provisioner_aliyun.go
  virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
  virtualcluster/pkg/controller/controllers/suite_test.go
  virtualcluster/pkg/controller/controllers/virtualcluster_controller.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/M

#241 🐛 Fix non-leader crashloop
  virtualcluster/cmd/syncer/app/server.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/M

#245 🐛 Fix a corner case that cluster gets partially deleted and ends up w…
  virtualcluster/pkg/syncer/syncer.go
Labels: size/XS, cncf-cla: yes, approved, lgtm

#246 🐛 Fix cancel function nil problem
  virtualcluster/pkg/util/cluster/cluster.go
Labels: size/XS, cncf-cla: yes, approved, lgtm

#249 🌱 Update go.mod k8s deps
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, lgtm, size/M

#250 🌱 Update vn-agent server test deps
  virtualcluster/pkg/vn-agent/server/test/go.sum
Labels: cncf-cla: yes, size/XL, approved, lgtm

#252 ✨Enabling Metrics for vn-agent
  virtualcluster/cmd/vn-agent/app/options/options.go
  virtualcluster/cmd/vn-agent/app/server.go
  virtualcluster/pkg/vn-agent/server/metrics.go
  virtualcluster/pkg/vn-agent/server/route.go
  virtualcluster/pkg/vn-agent/server/server.go
Labels: ok-to-test, cncf-cla: yes, size/L, approved, lgtm

#244 📖add quota validation plugin proposal
  docs/proposals/20220206-quota.md
  docs/proposals/images/quota/plugin.png
Labels: cncf-cla: yes, size/L, approved, lgtm

#253 📖🌱Update Proposal header to conform with template
  docs/proposals/20220206-quota.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#254 ✨ Adding Support for Mutating DNSPolicy
  virtualcluster/pkg/syncer/constants/constants.go
  virtualcluster/pkg/syncer/conversion/helper_test.go
  virtualcluster/pkg/syncer/conversion/mutate.go
  virtualcluster/pkg/syncer/conversion/mutate_test.go
  virtualcluster/pkg/syncer/util/featuregate/gate.go
Labels: cncf-cla: yes, size/XL, approved, lgtm
