Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2022-08, with the labels that each got.

#298 ✨Support exposing single annotations/labels via env downward API
  virtualcluster/pkg/syncer/conversion/mutate.go
  virtualcluster/pkg/syncer/conversion/mutate_test.go
Labels: kind/feature, cncf-cla: yes, needs-ok-to-test, approved, lgtm, size/M

#299 🌱 Update CRD Clients to v1
  virtualcluster/pkg/syncer/conversion/equality.go
  virtualcluster/pkg/syncer/conversion/helper.go
  virtualcluster/pkg/syncer/resources/crd/checker.go
  virtualcluster/pkg/syncer/resources/crd/controller.go
  virtualcluster/pkg/syncer/resources/crd/uws.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#300 🌱 Remove excess NodeInfo.OperatingSystem assign
  virtualcluster/pkg/syncer/vnode/vnode.go
Labels: size/XS, cncf-cla: yes, approved, lgtm
