Repository kubernetes-sigs/cluster-api-provider-nested, pull requests merged in 2022-04, with the labels that each got.

#267 🌱 Switching to golangci-lint via actions
  .github/workflows/golangci-lint.yml
  api/v1alpha4/zz_generated.deepcopy.go
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controlplane/nested/api/v1alpha4/zz_generated.deepcopy.go
  controlplane/nested/config/crd/bases/controlplane.cluster.x-k8s.io_nestedapiservers.yaml
  controlplane/nested/config/crd/bases/controlplane.cluster.x-k8s.io_nestedcontrollermanagers.yaml
  controlplane/nested/config/crd/bases/controlplane.cluster.x-k8s.io_nestedetcds.yaml
  controlplane/nested/config/rbac/role.yaml
  scripts/ci-test.sh
  scripts/fetch_ext_bins.sh
  virtualcluster/Makefile
  virtualcluster/experiment/pkg/apis/cluster/v1alpha4/zz_generated.deepcopy.go
  virtualcluster/pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#261 Add DnsOption Flag to allow user to have customized resolve.conf
  controlplane/nested/main.go
  go.mod
  go.sum
  main.go
  virtualcluster/cmd/syncer/app/options/options.go
  virtualcluster/pkg/syncer/apis/config/types.go
  virtualcluster/pkg/syncer/conversion/mutate.go
  virtualcluster/pkg/syncer/conversion/mutate_test.go
  virtualcluster/pkg/syncer/resources/pod/dws.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#266 transfer k8s api to meet new version
  virtualcluster/config/crd/tenancy.x-k8s.io_clusterversions.yaml
  virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/M

#268 Remove deprecated annotation for SVC, it block the installation of etcd
  virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
  virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
  virtualcluster/pkg/controller/controllers/clusterversion_controller_test.go
  virtualcluster/test/e2e/framework/clusterversion/create.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/S

#270 🐛 Github Actions goreleaser fixes
  .github/workflows/golangci-lint.yml
  controlplane/nested/controllers/controller_util.go
  controlplane/nested/main.go
  main.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#269 ✨ Adding VN Agent PodIP Provider
  virtualcluster/cmd/syncer/app/options/options.go
  virtualcluster/pkg/syncer/apis/config/types.go
  virtualcluster/pkg/syncer/util/featuregate/gate.go
  virtualcluster/pkg/syncer/vnode/pod/provider.go
  virtualcluster/pkg/syncer/vnode/pod/provider_test.go
  virtualcluster/pkg/syncer/vnode/vnode.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#223 use namespace as kubeletclient cert cn because vn-agent expects that for kubectl exec
  controlplane/nested/certificate/helpers.go
  controlplane/nested/controllers/nestedapiserver_controller.go
Labels: ok-to-test, size/XS, cncf-cla: yes, approved, lgtm
